# Generated by Django 4.0.5 on 2022-08-18 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_remove_ticket_image_photo_ticket_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.CharField(choices=[('One Star', 'One Star'), ('Two Stars', 'Two Stars'), ('Three Stars', 'Three Stars'), ('Four Stars', 'Four Stars'), ('Five Stars', 'Five Stars')], max_length=20),
        ),
        migrations.AlterField(
            model_name='review',
            name='ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='review.ticket'),
        ),
        migrations.DeleteModel(
            name='UserFollows',
        ),
    ]
